### ISSUE TITLE
has been blocked by CORS policy

### ISSUE THREAD

**Issue by avildema** [volverjs/auth-vue#11]
Hi,

I have app on VUE3:

service/AuthService.js
```js
import { SessionStorage, OAuthClient } from '@volverjs/auth-vue'
const authClient  = new OAuthClient({
  // The URL of the OAuth issuer
  url: 'https://my.com/adfs',
  // The client id of the application
  clientId: 'my_client_id',
  // The client authentication method, default: 'none'
  // Are also supported: 'client_secret_basic', 'client_secret_post' and 'private_key_jwt'
  tokenEndpointAuthMethod: 'client_secret_post',
  // The scopes requested to the OAuth server
  scopes: 'openid profile email allatclaims',
  // The storage to use for persisting the refresh token, default: new LocalStorage('oauth')
  storage: new SessionStorage('my-session-storage'),
  // The redirect URI of the application, default: document.location.origin
  redirectUri: 'http://localhost:5173/callback'
  })
authClient._client.client_secret = 'my_secret'
export default authClient
```
views/Auth/Auth.vue

```vue
<template>
  <div>
    Test
    <v-btn @click="signIn">Sign in</v-btn>
  </div>
</template>

<script>
import {onMounted} from "vue";
import authClient from "@/service/AuthService";

export default {
  setup(){

    const signIn = () => {
      authClient.authorize()
      //authClient.handleCodeResponse()
    }


    onMounted(()=>{
      console.log("initializing...");
      authClient.initialize()
      console.log("initialized...");
    })

    return{
      signIn
    }
  }
}
</script>

<style lang="scss" scoped>

</style>
```

views/Auth/Callback.vue

```vue
<template>
    <div>
      Test
      <v-btn @click="signIn">handleCode</v-btn>
    </div>
  </template>

  <script>
  import {onMounted} from "vue";
  import authClient from "@/service/AuthService";

  export default {
    setup(){


      onMounted(()=>{
        console.log("initializing...");
        authClient.initialize()
        console.log("initialized...");
      })

    }
  }
  </script>

  <style lang="scss" scoped>

  </style>
```

I got `code` from my adfs and app redirect to callback
And on Callback I get CORS error , while plugin send POST request I got the following error:

Access to fetch at 'https://my.com/adfs/oauth2/token/' from origin 'http://localhost:5173' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

POST https://my.com/adfs/oauth2/token/ net::ERR_FAILED 200 (OK)

Uncaught (in promise) TypeError: Failed to fetch
    at authenticatedRequest (index.js:825:12)
...

I use latest version

**Comment by stefano24** [comment]
Hi @avildema! Thanks for using @volverjs/auth-vue.
This problem is not related to the library.
When @volverjs/auth-vue receive the "code" response, it tries to get the token.
To solve the problem you need to add the client URL "http://localhost:5173" to access control allow origin header server response. In your case: `Access-Control-Allow-Origin: http://localhost:5173`.
To find more information about this topic you can read https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by avildema** [comment]
@stefano24 thank you for response!

I see on library and does not  see parameters for `getToken` header 
may be you have some example for vue3+vite+@volverjs/auth-vue

**Comment by stefano24** [comment]
Hi @avildema, sorry, I don't understand your question. What do you mean with "getToken" parameter?

We plan to add an example on volverjs/ui-vue-starter repo.

**Comment by avildema** [comment]
@stefano24 

authorizationCodeGrantRequest doesn't pass `options` for use it for add `Access-Control-Allow-Origin: http://localhost:5173` to header 

may be I don't understand how to add access-control-allow-origin to header inside oauth2/token request

my call stack:

OAuthClient.js: 
```js
const s = await i.authorizationCodeGrantRequest(
        this._authorizationServer,
        this._client,
        r,
        this._redirectUri,
        this._codeVerifier.value
      );
```
from oauth4webapi:
```js
export async function authorizationCodeGrantRequest(as, client, callbackParameters, redirectUri, codeVerifier, options) {
    assertAs(as);
    assertClient(client);
    if (!branded.has(callbackParameters)) {
        throw new TypeError('"callbackParameters" must be an instance of URLSearchParams obtained from "validateAuthResponse()", or "validateJwtAuthResponse()');
    }
    if (!validateString(redirectUri)) {
        throw new TypeError('"redirectUri" must be a non-empty string');
    }
    if (!validateString(codeVerifier)) {
        throw new TypeError('"codeVerifier" must be a non-empty string');
    }
    const code = getURLSearchParameter(callbackParameters, 'code');
    if (!code) {
        throw new OPE('no authorization code in "callbackParameters"');
    }
    const parameters = new URLSearchParams(options?.additionalParameters);
    parameters.set('redirect_uri', redirectUri);
    parameters.set('code_verifier', codeVerifier);
    parameters.set('code', code);
    return tokenEndpointRequest(as, client, 'authorization_code', parameters, options);
}
```

**Comment by stefano24** [comment]
Hi @avildema, the header `Access-Control-Allow-Origin` must be added on the response (server side), not from the client side as an option.
